Dashing devel
ros-teleop/twist_mux pull request #18
Opened 2020-03-17 11:59 UTC by brightenlee

Ported except joystick_relay node

2020-04-06 15:47 UTC, bmagyar requested changes
Unfortunately github is not intelligent enough to connect the files you renamed in the diff view. Please undo the renaming of `.h` files to `.hpp` so I can properly assess the changes.

2020-04-06 15:47 UTC, bmagyar commented on CMakeLists.txt
> +if (BUILD_TESTING)
please either uncomment or delete the commented stuff

2020-04-06 15:47 UTC, bmagyar commented on include/twist_mux/twist_mux.hpp
> +  // RCLCPP_SMART_PTR_DEFINITIONS(TwistMux);
commented stuff

2020-04-06 15:48 UTC, bmagyar commented on test/test_foo.py
> +def test_foo():
how about removing this?

2020-04-06 15:48 UTC, bmagyar commented on test/system_blackbox.py
> +        # TODO wait_for_msg-like functionnality not yet available
```suggestion
        # TODO wait_for_msg-like functionality not yet available
```

2020-04-06 15:50 UTC, bmagyar commented on test/system_blackbox.py
> +        # https://github.com/ros2/rclcpp/issues/520
These in-code TODO-s will be forgotten and never addressed. Could you please instead open an issue on github with some detail and put `TODO: link....` here?

2020-04-06 15:50 UTC, bmagyar commented on test/system_blackbox.py
> +        # TODO(artivis) use rate once available
These in-code TODO-s will be forgotten and never addressed. Could you please instead open an issue on github with some detail and put `TODO: link....` here?

2020-04-06 15:50 UTC, bmagyar commented on src/twist_mux_diagnostics.cpp
> +  //  ROS_DEBUG_THROTTLE(1.0, "Publishing diagnostics.");
commented code, please eithe rremove or fix

2020-05-04 12:37 UTC, MRedel21 commented
how about with ROS2 eloquent?

2020-07-10 21:15 UTC, Michael-Equi commented
@bmagyar  Is this ready to be merged yet? Looks like it has been sitting a bit and the ros-planning/dashing-devel branch is still at ROS1 stuff.

2023-05-30 08:58 UTC, closed without merging